# DI for JSON data files generator related setup


services:

  # Event JSON data file generator command
  app.fileGenerator.event.command:
    class: \Phpsw\Website\DataFileGenerator\GenerateEventFileCommand
    autowire: true
    tags:
      - {name: "ConsoleCommand" }

  # Event JSON data file generator
  app.fileGenerator.event:
    class: \Phpsw\Website\DataFileGenerator\EventFileGenerator
    autowire: true

  # Talk JSON data file generator command
  app.fileGenerator.talk.command:
    class: \Phpsw\Website\DataFileGenerator\GenerateTalkFileCommand
    autowire: true
    tags:
      - {name: "ConsoleCommand" }

  # Talk JSON data file generator
  app.fileGenerator.talk:
    class: \Phpsw\Website\DataFileGenerator\TalkFileGenerator
    autowire: true

  # Person JSON data file generator command
  app.fileGenerator.person.command:
    class: \Phpsw\Website\DataFileGenerator\GeneratePersonFileCommand
    autowire: true
    tags:
      - {name: "ConsoleCommand" }

  # Person JSON data file generator
  app.fileGenerator.person:
    class: \Phpsw\Website\DataFileGenerator\PersonFileGenerator
    autowire: true

  # The Meetup API client
  app.meetupApiClient:
    class: \Phpsw\Website\DataFileGenerator\MeetupApiClient
    autowire: true
    arguments: ["%meetupApiKey%"]
