# DI for website generator related setup

services:

  # Entry point to website generator
  app.websiteGenerator:
    class: \Phpsw\Website\WebsiteGenerator\WebsiteGenerator
    autowire: true

  # Value object that holds the base directory for
  app.websiteGenerator.baseDirectory:
    class: \Phpsw\Website\WebsiteGenerator\WebsiteBaseDirectory
    arguments: ["%websiteBaseDirectory%"]

  app.websiteGenerator.twigWrapper:
    class: \Phpsw\Website\WebsiteGenerator\TemplateRenderer\TwigWrapper
    autowire: true

  # Register twig extensions
  app.websiteGenerator.twigExtension.url:
    class: \Phpsw\Website\WebsiteGenerator\TemplateRenderer\TwigExtension\UrlTwigExtension
    autowire: true
    tags:
      - {name: "TwigExtension"}

  app.websiteGenerator.twigExtension.date:
    class: \Phpsw\Website\WebsiteGenerator\TemplateRenderer\TwigExtension\DateTwigExtension
    autowire: true
    tags:
      - {name: "TwigExtension"}


  # Register content type generators
  app.websiteGenerator.contentTypeGenerator.events:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\EventPagesGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}

  app.websiteGenerator.contentTypeGenerator.home:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\HomePageGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}

  app.websiteGenerator.contentTypeGenerator.speakers:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\SpeakerPagesGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}

  app.websiteGenerator.contentTypeGenerator.sponsors:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\SponsorsPageGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}

  app.websiteGenerator.contentTypeGenerator.staticPages:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\StaticPagesGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}

  app.websiteGenerator.contentTypeGenerator.talks:
    class: \Phpsw\Website\WebsiteGenerator\ContentTypeGenerator\TalkPagesGenerator
    autowire: true
    tags:
      - {name: "ContentTypeGenerator"}


  # Website generator command
  app.websiteGenerator.command:
    class: \Phpsw\Website\WebsiteGenerator\GenerateWebsiteCommand
    autowire: true
    tags:
      - {name: "ConsoleCommand" }


